"""update db

Revision ID: 046574a94473
Revises: 71847053608d
Create Date: 2023-04-17 09:33:29.364317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046574a94473'
down_revision = '71847053608d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
