"""update db

Revision ID: 252ddb7f27c3
Revises: 03fa7aa7f3d3
Create Date: 2023-04-10 14:11:01.956410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252ddb7f27c3'
down_revision = '03fa7aa7f3d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
