"""create db

Revision ID: cf0a4ab0faf8
Revises: 
Create Date: 2023-04-12 12:18:03.374641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0a4ab0faf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('units', sa.String(length=10), nullable=True))
    op.add_column('recipe', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'user_id')
    op.drop_column('ingredient', 'units')
    # ### end Alembic commands ###
